### ISSUE TITLE
启动报错惹

### ISSUE THREAD

**Issue by ID114514** [MemoryDewey/genshin-bot#1]
$ nodemon --config nodemon.json
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): framework\**\* src\**\* main.ts
[nodemon] watching extensions: ts
[nodemon] starting `ts-node -r tsconfig-paths/register main.ts`
[2022-01-03T16:39:43.180] [INFO] default - Load RateModule success
[2022-01-03T16:39:43.183] [INFO] default - Load WishExportModule success
Error: connect ECONNREFUSED 127.0.0.1:6700
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6700
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by MemoryDewey** [comment]
需要先安装[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)或者其他的支持[onebot](https://github.com/botuniverse/onebot)标准的插件哦

**Comment by ID114514** [comment]
> 需要先安装[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)或者其他的支持[onebot](https://github.com/botuniverse/onebot)标准的插件哦

啊，这个能兼容hoshino吗

**Comment by ID114514** [comment]
> 需要先安装[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)或者其他的支持[onebot](https://github.com/botuniverse/onebot)标准的插件哦

使用过go-cqhttp 的反向了

**Comment by MemoryDewey** [comment]
> 

需要使用正向ws哈，我更新一下文档

**Comment by MemoryDewey** [comment]
> > 需要先安装[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)或者其他的支持[onebot](https://github.com/botuniverse/onebot)标准的插件哦
> 
> 使用过go-cqhttp 的反向了

需要使用正向WS哈，默认接口是6700~我更新一下文档

**Comment by ID114514** [comment]
> > > 需要先安装[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)或者其他的支持[onebot](https://github.com/botuniverse/onebot)标准的插件哦
> > 
> > 
> > 使用过go-cqhttp 的反向了
> 
> 需要使用正向WS哈，默认接口是6700~我更新一下文档

欧克了，不过这个抽卡分析一直提示我参数错误怎么回事呀，导出的链接通过浏览器能正常打开，格式也一样的

**Comment by MemoryDewey** [comment]
> 
> 欧克了，不过这个抽卡分析一直提示我参数错误怎么回事呀，导出的链接通过浏览器能正常打开，格式也一样的

后续我跟进一下，更新好后回复你

**Comment by ID114514** [comment]
> > 欧克了，不过这个抽卡分析一直提示我参数错误怎么回事呀，导出的链接通过浏览器能正常打开，格式也一样的
> 
> 后续我跟进一下，更新好后回复你

好的

**Comment by MemoryDewey** [comment]
> 
> 好的
已在最新的master分支上更新，拉取新的代码重新试试

**Comment by MemoryDewey** [comment]
> 
> 好的

已在最新的master分支上更新，拉取新的代码重新试试

**Comment by ID114514** [comment]
> > 好的
> 
> 已在最新的master分支上更新，拉取新的代码重新试试

欧克
